name: Test and Coverage

on:
  push:
    branches:
      - '*'

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: default_database_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USERNAME: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: default_database_test

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: build php container
      run: docker build -t php-container -f Dockerfile .

    # if you need to call composer install, uncomment these lines
    # - name: Set up PHP Container
    #   run: |
    #     docker run --rm -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_PORT=$MYSQL_PORT -e MYSQL_USERNAME=$MYSQL_USERNAME -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -v ${{ github.workspace }}:/app php-container composer install

    - name: run transition
      run: |
        docker run --rm --network host -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_PORT=$MYSQL_PORT -e MYSQL_USERNAME=$MYSQL_USERNAME -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -v ${{ github.workspace }}:/var/www/html php-container bin/cake transition

    - name: run phpunit tests
      run: |
        docker run --rm --network host -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_PORT=$MYSQL_PORT -e MYSQL_USERNAME=$MYSQL_USERNAME -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -v ${{ github.workspace }}:/var/www/html php-container vendor/bin/phpunit --stop-on-failure

    # run tests and upload coverage:
    # - name: run phpunit tests with coverage
    #   run: |
    #     docker run --rm --network host -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_PORT=$MYSQL_PORT -e MYSQL_USERNAME=$MYSQL_USERNAME -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -v ${{ github.workspace }}:/app php-container phpunit --coverage-clover build/logs/clover.xml

    # - name: Upload Coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     file: build/logs/clover.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}

