name: Block Direct Pushes

on:
  push:
    branches:
      - master

jobs:
  block_direct_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check for Pull Request
      run: |
        if [[ $GITHUB_EVENT_NAME == "push" && -z "$GITHUB_EVENT_PATH" ]]; then
          echo "Direct pushes to master are not allowed. Please use pull requests."
          exit 1
        fi
